all: boundary_pruning.cpp boundary_pruning.h Makefile
	g++ boundary_pruning.cpp -lrt -lm -O3 -o tester 

debug: boundary_pruning.cpp boundary_pruning.h Makefile
	g++ boundary_pruning.cpp -lrt -lm -g -o debug -O0
